name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Remove existing files in the gh-pages branch except .nojekyll
          git checkout --orphan gh-pages
          git reset --hard
          git add -A
          git commit -m "Deploy to GitHub Pages"

          # Push changes to the gh-pages branch
          git push -f origin gh-pages
